name = "telegram-worker-bot"
main = "worker.js"
workers_dev = true
preview_urls = true
compatibility_date = "2025-09-16"

[[routes]]
pattern = "bot.turksafar.ir"
zone_name = "turksafar.ir"
custom_domain = true

[site]
bucket = "./src"
