name = "telegram-worker-bot"
main = "./src/worker.js"          # Entry point
workers_dev = true                # Enable *.workers.dev
preview_urls = true               # Show preview URLs on deploy
compatibility_date = "2024-01-01" # Cloudflare runtime compatibility date

# Compatibility flags
compatibility_flags = [
    "enable_nodejs_process_v2",
    "enable_nodejs_http_server_modules",
    "enable_nodejs_http_modules",
    "enable_navigator_language",
    "enable_top_level_await_in_require",
    "nodejs_compat",
]

# Placement
[placement]
mode = "smart"

[[routes]]
pattern = "bot.turksafar.ir" # Custom domain for the worker
zone_name = "turksafar.ir"
custom_domain = true

# Static assets configuration
[assets]
directory = "./src" # Serve static files from src
binding = "ASSETS"  # Binding name used in code

[observability.logs]
enabled = true

# Optional: D1 database binding (create DB first, then fill database_id)
# [[d1_databases]]
# binding = "DB"
# database_name = "USER_TOKENS"
# database_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"

[[d1_databases]]
binding = "DB"
database_name = "USER_TOKENS"
database_id = "d97439cc-70bf-4728-af91-f0dbb38e9a14" # Replace with actual ID
